# platform settings
dist: trusty
language:
  - ruby
  - java
jdk: openjdk8
rvm:
  - 2.7

# cache ruby deps
cache: bundler

# git settings
git:
  submodules: false
branches:
  only:
  - master

# ci/cd
install: bundle install

script:
  - jekyll build

after_success:
#  - source /opt/jdk_switcher/jdk_switcher
#  - jdk_switcher use openjdk8
  - s3_website push --verbose
